##############################################
# configuration file for instabrain feedback #
##############################################

watch_folder: /path/to/watch
subject_folder: /path/to/subject
