###############################
# instabrain localizer config #
###############################

SUBJECT_DIR: /Users/eo5629/fmri/seqlearn
NUM_RUNS: 10
VOLS_PER_RUN: 160
TR: 2.0
ZSCORE_TRS: 10
TRS_PER_TRIAL: 10
TRIAL_FEATURE_TRS: [5,7] #from a to b
PRESSES_PER_TRIAL: 1
