###############################
# instabrain localizer config #
###############################

SUBJECT_DIR: /Users/eo5629/fmri/seqlearn
NUM_RUNS: 6
VOLS_PER_RUN: 150
TR: 2.0
TRS_PER_TRIAL: 5
TRIAL_FEATURE_TRS: [3,5] #from a to b
PRESSES_PER_TRIAL: 10
