###############################################
# configuration file for instabrain localizer #
###############################################

SUBJECT_DIR: /Users/eo5629/fmri/seqlearn/
NUM_RUNS: 8
VOLS_PER_RUN: 125
TR: 2.0
TRS_PER_TRIAL: 5
MOVING_AVERAGE_TRS: 3
TRS_TRIAL_END_OFFSET: 0

