#############################################
# configuration file for instabrain backend #
#############################################

# file processing
watch-dir: /home/skyrahost/sambashare #/home/instabrain/mridump
recon-script: /home/instabrain/recon-scripts/runLocal_CPU_copy.sh
archive-data: True
archive-dir : /home/instabrain/mridump #/Users/el27322/Documents/instabrain_test/mridump

# networking
post-url: http://169.254.137.200:5000/rt_data #http://127.0.0.1:5000/rt_data

# imaging params
baseline-trs: 10

# data processing
moving-avg-trs: 2
mc-mode: afni # or fsl

# MRI sequence
multiband: True

# feedback mode
feedback-mode: intermittent

# intermittent feedback
trials-per-run: 20
cue-trs: 5
wait-trs: 1
feedback-trs: 1
iti-trs: 4
