#############################################
# configuration file for instabrain backend #
#############################################

# file processing
watch-dir: /home/realtime/10GbDump
recon-script: /home/realtime/remoteServer/ejaMBRemoteICE-R007/runLocal_CPU_copy.sh
archive-data: True

# networking
post-url: http://169.254.137.200:5000/rt_data #http://127.0.0.1:5000/rt_data

# imaging params
baseline-trs: 5 #10
feedback-trs: 155 #150

# data processing
moving-avg-trs: 3
mc-mode: fsl # or afni

# MRI sequence
multiband: True
