#############################################
# configuration file for instabrain backend #
#############################################

# file processing
watch-dir: /home/instabrain/mridump
recon-script: /home/instabrain/recon-scripts/runLocal_CPU_copy.sh
archive-data: True

# networking
post-url: http://169.254.137.200:5000/rt_data
dashboard-base-url: http://127.0.0.1:5000

# imaging params
baseline-trs: 10

# data processing
moving-avg-trs: 3
mc-mode: afni

# MRI sequence
multiband: True

# feedback mode
feedback-mode: intermittent

# intermittent feedback
trials-per-run: 20
cue-trs: 6
wait-trs: 1
feedback-trs: 1
iti-trs: 0