#################################
# configuration file for smoker #
#################################

# directory where incoming images appears
watch-dir: /home/realtime/10GbDump
recon-server-path: /home/realtime/remoteServer/ejaMBRemoteICE-R007
archive-data: True

# port where summarized brain data is served
server-port: 27000

# imaging params
trials-per-run: 15
tr-time: 2.0 #seconds
zscore-trs: 10
cue-trs: 3
wait-trs: 4
feedback-trs: 1
iti-trs: 3
moving-avg-trs: 3

# websocket server params
ws-server-host: 0.0.0.0
ws-server-port: 8080
ws-server-name: smoker