################################
# feedback display config file #
################################

# server params
shutdown-url: 'http://127.0.0.1:5000/shutdown'

# imaging params
runs: 12
trials-per-run: 15
tr-time: 2.0 #seconds
zscore-trs: 10
cue-trs: 3
wait-trs: 3.5 #4
feedback-trs: 1
iti-trs: 2.5 #3

# classifier params
num-classes: 5

# display params
fullscreen: False #True
feedback-update-trs: 0.25 #<feedback-trs
fixation-diameter: 1.5 #degrees
min-feedback-diameter: 2 #degrees
max-feedback-diameter: 10 #degrees
feedback-indicator-diameter: 0.3 #degrees

# reward
max-experiment-reward: 30 # dollars
