################################
# feedback display config file #
################################

# server params
server-ip: 169.254.137.201
server-port: 27000

# websocket client params
ws-server-host: 0.0.0.0
ws-server-port: 8080
ws-client-name: brainHUD

# imaging params
runs: 12
trials-per-run: 15
tr-time: 2.0 #seconds
zscore-trs: 10
cue-trs: 3
wait-trs: 4
feedback-trs: 1
iti-trs: 3

# debug imaging params
# trials-per-run: 3
# tr-time: 0.5
# zscore-trs: 1

# display params
fullscreen: False #True
feedback-update-trs: 0.25 #<feedback-trs
fixation-diameter: 1.5 #degrees
min-feedback-diameter: 2 #degrees
max-feedback-diameter: 10 #degrees
feedback-indicator-diameter: 0.3 #degrees

# key inputs
input-mode: qwerty # qwerty, sensor

# reward
max-experiment-reward: 30 # dollars
