#############################################
# configuration file for instabrain backend #
#############################################

# debugging
debug-bool: True

# directory where incoming images appears
watch-dir: /home/realtime/10GbDump
recon-script: /home/realtime/remoteServer/ejaMBRemoteICE-R007/runLocal_CPU_copy.sh
archive-data: True

# networking
post-url: http://127.0.0.1:5000/rt_data/

# imaging params
trials-per-run: 15
tr-time: 2.0 #seconds
zscore-trs: 10
cue-trs: 3
wait-trs: 4
feedback-trs: 1
iti-trs: 2
moving-avg-trs: 3
